### ISSUE TITLE
No handlers could be found for logger "pyxmpp2.resolver"

### ISSUE THREAD

**Issue by stayliv3** [Jajcus/pyxmpp2#86]
run the example meet the error.

`No handlers could be found for logger "pyxmpp2.resolver"`

installed by `git clone` and `python setup install`   

test on mac and kali

**Comment by Jajcus** [comment]
It is not an error, just a warning from the logging subsystem. Configure the logging properly (see: https://docs.python.org/3.5/library/logging.html) and the message will go away.

Some of the PyXMPP2 examples include logging configuration code.

**Comment by stayliv3** [comment]
thanks，I will try it.
