### ISSUE TITLE
error: too few arguments

### ISSUE THREAD

**Issue by Aravinthu** [Jajcus/pyxmpp2#88]
when i'm tring to run ($ sudo python error: roster.py). i'm getting this log

usage: roster.py [-h] [--starttls] [--tls-cacert-file TLS_CACERT_FILE]
              [--tls-require] [--ipv6] [--tls-verify-peer]
              [--c2s-port C2S_PORT] [--insecure-auth] [--password PASSWORD]
              [--prefer-ipv6] [--server SERVER] [--debug] [--quiet] [--trace]
              [--roster-cache ROSTER_CACHE]
              JID {show,monitor,add,remove,update} ...
roster.py: error: too few arguments

**Comment by Jajcus** [comment]
That is not an error, just usage instruction.

BTW you should never use 'sudo' to call PyXMPP examples (like for any other random code from the internet).

**Comment by Aravinthu** [comment]
do u have any example for muc, bcoz i tried send_message_client.py working fine for me, but i like send message to group, pls help.
